added support for timestamp types
VerizonAdPlatforms/bandar-log pull request #44
Opened 2020-11-17 16:55 UTC by MaksymSkrynnikov

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

By default REALTIME_LAG calculated as NOW (epoch millis) - MAX(timestamp) from SQL, added support to be able to operate not only in milliseconds but in hours as well.

2020-11-17 16:59 UTC, rossoha approved these changes

2020-11-17 17:49 UTC, gemelen commented on bandarlog/src/main/scala/com/aol/one/dwh/bandarlog/providers/SqlProvider.scala
> +        case Some("hour") => Instant.now().getEpochSecond / 3600L
I'm sure that input could be treated more liberal than exact match of "hour" string.

2020-11-17 17:57 UTC, gemelen requested changes

2020-11-17 17:57 UTC, gemelen commented on bandarlog/src/main/scala/com/aol/one/dwh/bandarlog/providers/SqlProvider.scala
> +        case Some("hour") => Instant.now().getEpochSecond / 3600L
Also, what does this formula mean?
I do not understand how timestamp divided by constant is linked to hour range, so could you please explain it (probably with comment in source)?

2020-11-17 17:57 UTC, gemelen commented on infra/src/main/scala/com/aol/one/dwh/infra/config/Configs.scala
> +case class Table(table: String,
It seems to be an empty line was added here.

2020-11-17 17:57 UTC, gemelen commented on infra/src/main/scala/com/aol/one/dwh/infra/config/RichConfig.scala
> +      val columnType = obj.toConfig.getOptionalString("column-type").map(_.split(":")).getOrElse(Array("", ""))
Please, move chained operations in new lines.

2020-11-18 10:36 UTC, MaksymSkrynnikov commented on bandarlog/src/main/scala/com/aol/one/dwh/bandarlog/providers/SqlProvider.scala
> +        case Some("hour") => Instant.now().getEpochSecond / 3600L
Updated

2020-11-18 10:57 UTC, gemelen approved these changes

2020-11-18 11:33 UTC, merged